ALTER TABLE company
  ADD COLUMN short_name        TEXT,
  ADD COLUMN full_name         TEXT,
  ADD COLUMN entity_type       company_entity_type_enum,
  ADD COLUMN kpp               TEXT,
  ADD COLUMN ogrn              TEXT,
  ADD COLUMN legal_address     TEXT,
  ADD COLUMN director_name     TEXT,
  ADD COLUMN email             TEXT,
  ADD COLUMN phone             TEXT,
  ADD COLUMN contact_person    TEXT,
  ADD COLUMN marketplace       company_marketplace_enum,
  ADD COLUMN ozon_api_key      TEXT,
  ADD COLUMN ozon_warehouse_id TEXT,
  ADD COLUMN ym_api_key        TEXT,
  ADD COLUMN ym_warehouse_id   TEXT,
  ADD COLUMN edo_operator      company_edo_operator_enum,
  ADD COLUMN delivery_method   company_delivery_method_enum,
  ADD COLUMN delivery_city     TEXT,
  ADD COLUMN delivery_zone_id  UUID,
  ADD COLUMN purchase_limit    NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN status            company_status_enum NOT NULL DEFAULT 'onboarding',
  ADD COLUMN onboarding_step   INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN consents_accepted_at TIMESTAMPTZ,
  ADD COLUMN activated_at      TIMESTAMPTZ,
  ADD COLUMN manager_id        UUID REFERENCES "user"(id);
